### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by DerFetzer** [kinvolk/flatcar-linux-update-operator#27]
Hey guys,

there has not been any recent development activity on this repo.

Is the operator still maintained? Are there recommended replacements?
I've read about Nebraska but if I understand correctly it has to run outside of the cluster.

I am looking for a replacement of RancherOS in my cluster and having used CoreOS Container Linux in the past got me in touch with Flatcar Linux.

Thanks in advance!

**Comment by blixtra** [comment]
Yes. It's a core part of our Kubernetes offering, [Lokomotive](https://github.com/kinvolk/lokomotive). It currently works fine for us. If you find issues or have PR please file them and the team will review.

**Comment by invidian** [comment]
@DerFetzer let us know if you have further questions. Otherwise I'll close this issue.

**Comment by DerFetzer** [comment]
I have not finally decided on a replacement OS, yet. I will open a new ticket if I encounter any issues. Thank you very much!
